# Generated by Django 4.2 on 2023-05-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prompt', models.CharField(max_length=100)),
                ('Response', models.CharField(max_length=100)),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
